/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listoffiles;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 0wew0
 */
public class MainWindow extends javax.swing.JFrame {

    private ArrayList<String> filelist = new ArrayList<String>();
    public DefaultListModel filelistData = new DefaultListModel();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        FileNameExtensionFilter ff = new FileNameExtensionFilter("纯文本文档(*.txt)", "txt");
        saveChooser.setFileFilter(ff);
        saveChooser.setFileSelectionMode(0);
        
        
        fileChooser.setFileSelectionMode(1); 
        list_file.setModel(filelistData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        saveChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        text_dirAddress = new javax.swing.JTextField();
        btn_browse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_file = new javax.swing.JList();
        btn_start = new javax.swing.JButton();
        btn_copy = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_about = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        chk_cdir = new javax.swing.JCheckBox();
        txt_glq = new javax.swing.JTextField();
        btn_glq = new javax.swing.JButton();
        btn_glqhelp = new javax.swing.JButton();
        chk_glq = new javax.swing.JCheckBox();
        chk_dirname = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num_all = new javax.swing.JTextField();
        num_list = new javax.swing.JTextField();
        chk_isUnix = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("雅文件列表 v1.1");

        jLabel1.setText("文件夹路径：");

        btn_browse.setText("浏览");
        btn_browse.setToolTipText("");
        btn_browse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list_file);

        btn_start.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_start.setText("生成文件列表");
        btn_start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btn_copy.setText("复制列表到剪贴板");
        btn_copy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copyActionPerformed(evt);
            }
        });

        btn_save.setText("保存列表到文本文档");
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jButton6.setText("退出");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btn_about.setText("关于和更新");
        btn_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "zh-CN" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        chk_cdir.setText("扫描子文件夹");
        chk_cdir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_glq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_glq.setText("*");
        txt_glq.setEnabled(false);

        btn_glq.setText("筛选");
        btn_glq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_glq.setEnabled(false);
        btn_glq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_glqActionPerformed(evt);
            }
        });

        btn_glqhelp.setText("帮助");
        btn_glqhelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_glqhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_glqhelpActionPerformed(evt);
            }
        });

        chk_glq.setText("过滤器（通配符）：");
        chk_glq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chk_glq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_glqActionPerformed(evt);
            }
        });

        chk_dirname.setText("扫描文件夹名");
        chk_dirname.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("全部数据数量：");

        jLabel3.setText("列表数据数量：");

        num_all.setEditable(false);
        num_all.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num_all.setText("0");

        num_list.setEditable(false);
        num_list.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num_list.setText("0");

        chk_isUnix.setText("使用UNIX风格换行符");
        chk_isUnix.setToolTipText("不勾选则使用Windows风格换行符，Linux和OS X用户请勾选此项。");
        chk_isUnix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_dirAddress))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_copy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addComponent(chk_cdir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_glq)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_glq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_glqhelp))
                    .addComponent(chk_glq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk_dirname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_list))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_all))
                    .addComponent(btn_browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk_isUnix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_dirAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_cdir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_dirname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_isUnix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_copy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_glq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_glq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_glq)
                            .addComponent(btn_glqhelp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(num_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(num_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btn_about)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
        int option = fileChooser.showOpenDialog(null);
//        System.out.println("路径："+fileChooser.getSelectedFile().getPath());  
//        System.out.println("绝对路径："+fileChooser.getSelectedFile().getAbsolutePath());  
//        System.out.println("文件名称："+fileChooser.getSelectedFile().getName());  
//        String path = fileChooser.getSelectedFile().getAbsolutePath();
//        System.out.println("选择："+option); 
        if (option == 0) {
            String address = fileChooser.getSelectedFile().getAbsolutePath();
            text_dirAddress.setText(address);
        }
//FileChooser
    }//GEN-LAST:event_btn_browseActionPerformed

    private void chk_glqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_glqActionPerformed
        boolean ch = chk_glq.isSelected();
        txt_glq.setEnabled(ch);
        btn_glq.setEnabled(ch);
        if (!ch) {
            filelistData.removeAllElements();
            int n = 0;
            for (String nowStr : filelist) {
                filelistData.addElement(nowStr);
                n++;
            }
            num_list.setText(String.valueOf(n));
        } else {
            btn_glqActionPerformed(null);
        }
    }//GEN-LAST:event_chk_glqActionPerformed

    private void btn_glqhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_glqhelpActionPerformed
        JOptionPane.showMessageDialog(null, "快速指南：例如想找出所有txt文件，可以输入“*.txt”。\n\n通配符是一类键盘字符，有星号(*)和问号(?)。\n当查找文件夹时，可以使用它来代替一个或多个真正字符；\n当不知道真正字符或者不想键入完整名字时，常常使用通配符代替一个或多个真正字符。\n\n星号（*）\n可以使用星号代替0个或多个字符。\n如果正在查找以AEW开头的一个文件，但不记得文件名其余部分，可以输入AEW*，查找以AEW开头的所有文件类型的文件，\n如AEWT.txt、AEWU.EXE、AEWI.dll等。要缩小范围可以输入AEW*.txt，\n查找以AEW开头的所有文件类型并.txt为扩展名的文件\n如AEWIP.txt、AEWDF.txt。\n\n问号（？）\n可以使用问号代替一个字符。\n如果输入love?，查找以love开头的一个字符结尾文件类型的文件，\n如lovey、lovei等。\n要缩小范围可以输入love?.doc，查找以love开头的一个字符结尾文件类型并.doc为扩展名的文件\n如lovey.doc、loveh.doc。", "通配符使用帮助（选自百度百科）", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btn_glqhelpActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        if (text_dirAddress.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "还没有指定路径。", "缺少参数", JOptionPane.ERROR_MESSAGE);
        } else {
            Thread fl = new FileList(this, text_dirAddress.getText(), chk_cdir.isSelected(), chk_dirname.isSelected());
//        fl.b_cdir = chk_cdir.isSelected();
//        fl.b_dirname = chk_dirname.isSelected();
//        fl.mw = this;
        //Thread thread = new FileList();
        btn_start.setText("处理中……");
        num_all.setText("0");
        num_list.setText("0");
        ena(false);
        //this.setEnabled(false);
        fl.start();
        }
        
        //fl.start();
//        filelist = fl.list(text_dirAddress.getText(),b_cdir,b_dirname);
//        filelistData.removeAllElements();
//        filelistData.removeAllElements();
//        for (int i = 0; i < filelist.size(); i++) {
//            String nowStr = filelist.get(i);
//            filelistData.addElement(nowStr);
//        }
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_glqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_glqActionPerformed
        Wildcards wil = new Wildcards();
        filelistData.removeAllElements();
        int n = 0;
        for (String nowStr : filelist) {
            if (Wildcards.match(txt_glq.getText(),nowStr)) {
                filelistData.addElement(nowStr);
                n++;
            }
            //System.out.println(nowStr + " = " + Wildcards.match(txt_glq.getText(),nowStr));
        }
        num_list.setText(String.valueOf(n));
//        wil.tst();
    }//GEN-LAST:event_btn_glqActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        int option = saveChooser.showSaveDialog(null);
        if (option == 0) {
            String address = saveChooser.getSelectedFile().getAbsolutePath();
            File fp = new File(address);
            try {
                PrintWriter pfp = new PrintWriter(fp);
                pfp.print(copyStr());
                pfp.close();
            } catch (FileNotFoundException ex) {
                //Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "保存文件的时候出现问题了：" + ex, "文件保存失败", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copyActionPerformed
        StringSelection stringSelection = new StringSelection(copyStr());
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
    }//GEN-LAST:event_btn_copyActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        try {
            URI uri = new URI("http://uuu.moe/?p=1536");
            Desktop.getDesktop().browse(uri);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_aboutActionPerformed

    public void okList(ArrayList<String> filelisto) {
        //this.setEnabled(true);
        filelistData.removeAllElements();
        filelist = filelisto;
        for (String nowStr : filelisto) {
            try {
                filelistData.addElement(nowStr);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "由于数据量巨大，\n如果结果没有正确显示请关闭扫描子文件夹功能。", "异常：" + ex, JOptionPane.WARNING_MESSAGE);
            }
        }
        ena(true);
        btn_start.setText("生成文件列表");
    }
    
    private String copyStr() {
        String enterMode = "\r\n";
        if (chk_isUnix.isSelected()) {
            enterMode = "\n";
        }
        String copyStr = "";
        for (String nowStr : filelist) {
            if (copyStr.length() == 0) {
                copyStr = nowStr;
            } else {
                copyStr = copyStr + enterMode + nowStr;
            }
        }
        return copyStr;
    }
    
    public void setNum (boolean isAll) {
        if (isAll) {
            int num = Integer.parseInt(num_all.getText());
            num++;
            num_all.setText(String.valueOf(num));
        } else {
            int num = Integer.parseInt(num_list.getText());
            num++;
            num_list.setText(String.valueOf(num));
        }
    }
    
    private void ena (boolean isena) {
        if (!isena) {
            chk_glq.setSelected(isena);
            txt_glq.setEnabled(isena);
            btn_glq.setEnabled(isena);
        }
        chk_glq.setEnabled(isena);
        btn_start.setEnabled(isena);
        btn_copy.setEnabled(isena);
        btn_save.setEnabled(isena);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    private void exit() {
        dispose();
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_copy;
    private javax.swing.JButton btn_glq;
    private javax.swing.JButton btn_glqhelp;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_start;
    private javax.swing.JCheckBox chk_cdir;
    private javax.swing.JCheckBox chk_dirname;
    private javax.swing.JCheckBox chk_glq;
    private javax.swing.JCheckBox chk_isUnix;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list_file;
    private javax.swing.JTextField num_all;
    private javax.swing.JTextField num_list;
    private javax.swing.JFileChooser saveChooser;
    private javax.swing.JTextField text_dirAddress;
    private javax.swing.JTextField txt_glq;
    // End of variables declaration//GEN-END:variables
}
